/** Generated by YAKINDU Statechart Tools code generator. */
package org.yakindu.scr.localreactions;


public class LocalReactionsStatemachine implements ILocalReactionsStatemachine {
	protected class SCInterfaceImpl implements SCInterface {
	
		private long x;
		
		public long getX() {
			return x;
		}
		
		public void setX(long value) {
			this.x = value;
		}
		
		private long en_false;
		
		public long getEn_false() {
			return en_false;
		}
		
		public void setEn_false(long value) {
			this.en_false = value;
		}
		
		private long en_true;
		
		public long getEn_true() {
			return en_true;
		}
		
		public void setEn_true(long value) {
			this.en_true = value;
		}
		
		private long ex_true;
		
		public long getEx_true() {
			return ex_true;
		}
		
		public void setEx_true(long value) {
			this.ex_true = value;
		}
		
		private long ex_false;
		
		public long getEx_false() {
			return ex_false;
		}
		
		public void setEx_false(long value) {
			this.ex_false = value;
		}
		
	}
	
	protected SCInterfaceImpl sCInterface;
	
	private boolean initialized = false;
	
	public enum State {
		main_region_A,
		$NullState$
	};
	
	private final State[] stateVector = new State[1];
	
	private int nextStateIndex;
	
	
	public LocalReactionsStatemachine() {
		sCInterface = new SCInterfaceImpl();
	}
	
	public void init() {
		this.initialized = true;
		for (int i = 0; i < 1; i++) {
			stateVector[i] = State.$NullState$;
		}
		clearEvents();
		clearOutEvents();
		sCInterface.setX(0);
		
		sCInterface.setEn_false(0);
		
		sCInterface.setEn_true(0);
		
		sCInterface.setEx_true(0);
		
		sCInterface.setEx_false(0);
	}
	
	public void enter() {
		if (!initialized) {
			throw new IllegalStateException(
				"The state machine needs to be initialized first by calling the init() function."
			);
		}
		sCInterface.setEn_true(1);
		
		sCInterface.setEn_false(1);
		
		enterSequence_main_region_default();
	}
	
	public void runCycle() {
		if (!initialized)
			throw new IllegalStateException(
					"The state machine needs to be initialized first by calling the init() function.");
		clearOutEvents();
		for (nextStateIndex = 0; nextStateIndex < stateVector.length; nextStateIndex++) {
			switch (stateVector[nextStateIndex]) {
			case main_region_A:
				main_region_A_react(true);
				break;
			default:
				// $NullState$
			}
		}
		clearEvents();
	}
	public void exit() {
		exitSequence_main_region();
		sCInterface.setEx_true(1);
		
		sCInterface.setEx_false(1);
	}
	
	/**
	 * @see IStatemachine#isActive()
	 */
	public boolean isActive() {
		return stateVector[0] != State.$NullState$;
	}
	
	/** 
	* Always returns 'false' since this state machine can never become final.
	*
	* @see IStatemachine#isFinal()
	*/
	public boolean isFinal() {
		return false;
	}
	/**
	* This method resets the incoming events (time events included).
	*/
	protected void clearEvents() {
	}
	
	/**
	* This method resets the outgoing events.
	*/
	protected void clearOutEvents() {
	}
	
	/**
	* Returns true if the given state is currently active otherwise false.
	*/
	public boolean isStateActive(State state) {
	
		switch (state) {
		case main_region_A:
			return stateVector[0] == State.main_region_A;
		default:
			return false;
		}
	}
	
	public SCInterface getSCInterface() {
		return sCInterface;
	}
	
	public long getX() {
		return sCInterface.getX();
	}
	
	public void setX(long value) {
		sCInterface.setX(value);
	}
	
	public long getEn_false() {
		return sCInterface.getEn_false();
	}
	
	public void setEn_false(long value) {
		sCInterface.setEn_false(value);
	}
	
	public long getEn_true() {
		return sCInterface.getEn_true();
	}
	
	public void setEn_true(long value) {
		sCInterface.setEn_true(value);
	}
	
	public long getEx_true() {
		return sCInterface.getEx_true();
	}
	
	public void setEx_true(long value) {
		sCInterface.setEx_true(value);
	}
	
	public long getEx_false() {
		return sCInterface.getEx_false();
	}
	
	public void setEx_false(long value) {
		sCInterface.setEx_false(value);
	}
	
	/* 'default' enter sequence for state A */
	private void enterSequence_main_region_A_default() {
		nextStateIndex = 0;
		stateVector[0] = State.main_region_A;
	}
	
	/* 'default' enter sequence for region main region */
	private void enterSequence_main_region_default() {
		react_main_region__entry_Default();
	}
	
	/* Default exit sequence for state A */
	private void exitSequence_main_region_A() {
		nextStateIndex = 0;
		stateVector[0] = State.$NullState$;
	}
	
	/* Default exit sequence for region main region */
	private void exitSequence_main_region() {
		switch (stateVector[0]) {
		case main_region_A:
			exitSequence_main_region_A();
			break;
		default:
			break;
		}
	}
	
	/* Default react sequence for initial entry  */
	private void react_main_region__entry_Default() {
		enterSequence_main_region_A_default();
	}
	
	private boolean react() {
		return false;
	}
	
	private boolean main_region_A_react(boolean try_transition) {
		boolean did_transition = try_transition;
		
		if (try_transition) {
			if (react()==false) {
				did_transition = false;
			}
		}
		if (did_transition==false) {
			if (sCInterface.getX()==0) {
				sCInterface.setX(sCInterface.getX() + 1);
			}
		}
		return did_transition;
	}
	
}
